export const EXCHANGES_REQUEST = 'EXCHANGES_REQUEST';
export const EXCHANGES_SUCCESS = 'EXCHANGES_SUCCESS';
export const EXCHANGES_ERROR = 'EXCHANGES_ERROR';
export const EXCHANGES_UPDATE_FORM = 'EXCHANGES_UPDATE_FORM';
